# Generated by Django 5.0.3 on 2024-05-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='output_csv',
            new_name='output',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='output_pdf',
        ),
    ]
