# Generated by Django 5.0.3 on 2024-06-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_output_csv_uploadedfile_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='output_pdf',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
    ]
