"""
Django settings for brainweb project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fj+-3fb3v8+o!#9b2h$=bq*p5_zb^kpd8!*@4!klo&1di+oj@_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = []  # Development modunda 
else:
    ALLOWED_HOSTS = ['beyin.inonu.edu.tr','127.0.0.1', '10.16.2.42', 'localhost']  # Production modunda


# Application definition

INSTALLED_APPS = [
    'guest',
    'account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'brainweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR/'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brainweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Dil ve saat dilimi ayarları
LANGUAGES = [
    ('tr', _('Turkish')),
    ('en', _('English')),
]

LANGUAGE_CODE = 'tr'  # Türkçe dil kodu
TIME_ZONE = 'Europe/Istanbul'
USE_TZ = True  # Zaman dilimi kullanımı

USE_I18N = True
USE_L10N = True


LOCALE_PATHS = (
    BASE_DIR / 'locale',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

if DEBUG:
    STATIC_URL = '/static/'
    STATICFILES_DIRS=[
        BASE_DIR /'static'
    ]
else:
    STATIC_URL = '/static'
    STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#AUTH_USER_MODEL = 'account.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672/'


if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Debug modunda konsola yazdır
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Production modunda gerçek SMTP sunucusu kullan

EMAIL_HOST = 'smtp.gmail.com'  # SMTP sunucu adresi, production modunda değiştirin
EMAIL_PORT = 587  # SMTP sunucu portu, production modunda değiştirin
EMAIL_USE_TLS = True  # TLS kullanılacak mı?
EMAIL_HOST_USER = 'brainwebinonu@gmail.com'  # SMTP sunucu kullanıcı adı, production modunda değiştirin
EMAIL_HOST_PASSWORD = 'aevm jwia jkwm zuuy'  # SMTP sunucu parolası, production modunda değiştirin
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Varsayılan gönderen e-posta adresi