# Generated by Django 5.0.3 on 2024-04-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adı', models.CharField(max_length=100)),
                ('resim_küçük', models.ImageField(upload_to='hizmet_resimleri/küçük/')),
                ('açıklama_kısa', models.TextField()),
                ('resim_büyük', models.ImageField(upload_to='hizmet_resimleri/büyük/')),
                ('açıklama_uzun', models.TextField()),
                ('sayfadaki_sırası', models.IntegerField()),
                ('aktif_pasif', models.BooleanField(default=True)),
            ],
        ),
    ]
