# Generated by Django 5.0.3 on 2024-04-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='resim_küçük',
            field=models.ImageField(upload_to='hizmet_resimleri/kücük/'),
        ),
    ]
