# Generated by Django 5.0.3 on 2024-04-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_servis_resim_küçük'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servis',
            old_name='resim_küçük',
            new_name='resim_kücük',
        ),
    ]
