# Generated by Django 5.0.3 on 2024-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_rename_resim_küçük_servis_resim_kücük'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='resim_büyük',
            field=models.ImageField(upload_to='hizmet_resimleri/buyuk/'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='resim_kücük',
            field=models.ImageField(upload_to='hizmet_resimleri/kucuk/'),
        ),
    ]
