# Generated by Django 5.0.3 on 2024-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_alter_servis_resim_büyük_alter_servis_resim_kücük'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='model_pth_dosyası',
            field=models.FileField(default='', upload_to='model_files/'),
        ),
        migrations.AddField(
            model_name='servis',
            name='model_py_dosyası',
            field=models.FileField(default='', upload_to='model_files/'),
        ),
    ]
