# Generated by Django 5.0.3 on 2024-06-04 10:36

import guest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_servis_model_pth_dosyası_servis_model_py_dosyası'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='model_pth_dosyası',
            field=models.FileField(blank=True, default='', null=True, upload_to=guest.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='servis',
            name='model_py_dosyası',
            field=models.FileField(blank=True, default='', null=True, upload_to=guest.models.get_upload_path),
        ),
    ]
