# Generated by Django 5.0.3 on 2024-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_alter_servis_model_pth_dosyası_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='create_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
