# Generated by Django 5.0.3 on 2024-06-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_servis_create_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servis',
            old_name='create_pdf',
            new_name='pdf_oluştur',
        ),
    ]
