# Generated by Django 4.2.13 on 2024-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_rename_create_pdf_servis_pdf_oluştur'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='çalıştırılacak_servisler',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='çoklu_servis',
            field=models.BooleanField(default=False),
        ),
    ]
